apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dummy-component-button
  description: Artist Lookup
  tags:
    - ui
    - react
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  dependsOn: ['resource:artists-db']
